In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"],name="test1232131")
s

a    1.103736
b    0.897358
c    1.040495
d    0.240952
e    2.029429
Name: test1232131, dtype: float64

In [3]:
s.to_frame() # convert series to dataframe

test1232131
a     1.103736
b     0.897358
c     1.040495
d     0.240952
e     2.029429

In [4]:
s,s.T

(a    1.103736
 b    0.897358
 c    1.040495
 d    0.240952
 e    2.029429
 Name: test1232131, dtype: float64,
 a    1.103736
 b    0.897358
 c    1.040495
 d    0.240952
 e    2.029429
 Name: test1232131, dtype: float64)

In [5]:
s.to_frame().T # transpose

a         b         c         d         e
test1232131  1.103736  0.897358  1.040495  0.240952  2.029429

In [6]:
s.T # transpose ?

a    1.103736
b    0.897358
c    1.040495
d    0.240952
e    2.029429
Name: test1232131, dtype: float64

In [7]:
s["e"] = 10
s

a     1.103736
b     0.897358
c     1.040495
d     0.240952
e    10.000000
Name: test1232131, dtype: float64

In [11]:
# Column label with ()
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"],name="性别 (gender)")
d_s = s.to_frame()
d_s
d_s["性别 (gender)"]


a   -2.103677
b   -1.205918
c    0.561627
d    0.160177
e   -0.683297
Name: 性别 (gender), dtype: float64

In [12]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)
df

Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [19]:
df_con_col = pd.concat([df,df],ignore_index=True)
df_con_row = pd.concat([df,df],axis=1)
df_con_col
df_con_row

(                       Name  Age     Sex
 0   Braund, Mr. Owen Harris   22    male
 1  Allen, Mr. William Henry   35    male
 2  Bonnell, Miss. Elizabeth   58  female
 3   Braund, Mr. Owen Harris   22    male
 4  Allen, Mr. William Henry   35    male
 5  Bonnell, Miss. Elizabeth   58  female,
                        Name  Age     Sex                      Name  Age  \
 0   Braund, Mr. Owen Harris   22    male   Braund, Mr. Owen Harris   22   
 1  Allen, Mr. William Henry   35    male  Allen, Mr. William Henry   35   
 2  Bonnell, Miss. Elizabeth   58  female  Bonnell, Miss. Elizabeth   58   
 
       Sex  
 0    male  
 1    male  
 2  female  )

In [13]:
df_con_row

Name  Age     Sex                      Name  Age  \
0   Braund, Mr. Owen Harris   22    male   Braund, Mr. Owen Harris   22   
1  Allen, Mr. William Henry   35    male  Allen, Mr. William Henry   35   
2  Bonnell, Miss. Elizabeth   58  female  Bonnell, Miss. Elizabeth   58   

      Sex  
0    male  
1    male  
2  female

In [16]:
df.to_numpy(),df.to_numpy().shape,type(df.to_numpy())

(array([['Braund, Mr. Owen Harris', 22, 'male'],
        ['Allen, Mr. William Henry', 35, 'male'],
        ['Bonnell, Miss. Elizabeth', 58, 'female']], dtype=object),
 (3, 3),
 numpy.ndarray)

In [20]:
df['Age'],type(df['Age'])

(0    22
 1    35
 2    58
 Name: Age, dtype: int64,
 pandas.core.series.Series)

In [7]:
df.query("Sex in 'male'")

Name  Age   Sex
0   Braund, Mr. Owen Harris   22  male
1  Allen, Mr. William Henry   35  male

In [8]:
age_series = df['Age']

In [9]:
age_series.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: Age
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 152.0 bytes


In [13]:
pd.Series({"b":1,"a":0,"c":2}).index

Index(['b', 'a', 'c'], dtype='object')

In [24]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0, 5.0], index=["a", "b", "c","e"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

In [26]:
df = pd.DataFrame(d)
df

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
e  5.0  NaN

In [22]:
df.iloc[:3,1] #[:,:] first is row,second is column

a    1.0
b    2.0
c    3.0
Name: two, dtype: float64

 # From structured or record array


In [5]:
data = np.zeros((2,3))

In [6]:
pd.DataFrame(data)

0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0

In [7]:
data[:]= [(1, 2.0, 3.0), (2, 3.0, 4.0)]

In [8]:
data.shape

(2, 3)

In [9]:
df1 = pd.DataFrame(data)
df1

0    1    2
0  1.0  2.0  3.0
1  2.0  3.0  4.0

In [22]:
colume_data=["A","B","C"]

In [26]:
data_frame = pd.DataFrame(data,columns=colume_data)

In [27]:
data_frame.columns

Index(['A', 'B', 'C'], dtype='object')

In [28]:
data_frame.index

RangeIndex(start=0, stop=2, step=1)

In [29]:
df.columns

Index(['one', 'two'], dtype='object')

In [30]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [32]:
data_frame.index 

False

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   one     4 non-null      float64
 1   two     4 non-null      float64
dtypes: float64(2)
memory usage: 120.0+ bytes


In [34]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       2 non-null      float64
 1   B       2 non-null      float64
 2   C       2 non-null      float64
dtypes: float64(3)
memory usage: 176.0 bytes


# Create DataFrame from dict of Series or dicts

In [69]:
dict_series = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

In [70]:
df_dict_series = pd.DataFrame(dict_series)

In [71]:
df_dict_series

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [16]:
dict_dict = {"one":"ONE","two":"TWO","three":"THREE","four":"FOUR"}

In [17]:
index_dict_dict = pd.Index([1,2,3,4])
type(index_dict_dict)

pandas.core.indexes.base.Index

In [77]:
df_dict_dict = pd.DataFrame(dict_dict,index=index_dict_dict)

In [78]:
df_dict_dict

one  two  three  four
1  ONE  TWO  THREE  FOUR
2  ONE  TWO  THREE  FOUR
3  ONE  TWO  THREE  FOUR
4  ONE  TWO  THREE  FOUR

In [47]:
dict_dict = {"one":[1,2,3,4],"two":[5,6,7,8],"three":[9,10,11,12],"four":[13,14,15,16]}

In [48]:
df_dict_dict = pd.DataFrame(dict_dict,index=index_dict_dict)

In [49]:
df_dict_dict

one  two  three  four
1    1    5      9    13
2    2    6     10    14
3    3    7     11    15
4    4    8     12    16

In [54]:
df_dict_dict = pd.DataFrame(dict_dict,index=index_dict_dict,columns=["ONE","TWO","THREE","FOUR"])

In [55]:
df_dict_dict

ONE  TWO THREE FOUR
1  NaN  NaN   NaN  NaN
2  NaN  NaN   NaN  NaN
3  NaN  NaN   NaN  NaN
4  NaN  NaN   NaN  NaN

In [56]:
dict_dict = {"one":[1,2,3,4],"two":[5,6,7,8],"three":[9,10,11,12],"four":[13,14,15,16]}

In [57]:
df_dict_dict = pd.DataFrame(dict_dict,index=index_dict_dict)

In [58]:
df_dict_dict.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [60]:
df_dict_dict.columns[0]="ONE"

TypeError: Index does not support mutable operations

 # From dict of ndarrays / lists

In [62]:
dict_list =  {"one": [1.0, 2.0, 3.0, 4.0], "two": [4.0, 3.0, 2.0, 1.0]} 

In [65]:
df_dict_list = pd.DataFrame(dict_list)# Without Index object or list

In [66]:
df_dict_list

one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0

In [1]:
df_dict_list = pd.DataFrame(dict_list,index=["first","second","third"])# With Index object or list,but length is not matched

NameError: name 'pd' is not defined

In [68]:
df_dict_list = pd.DataFrame(dict_list,index=["first","second","third","four"])# With Index object or list

In [69]:
df_dict_list

one  two
first   1.0  4.0
second  2.0  3.0
third   3.0  2.0
four    4.0  1.0

# From a list of dicts

In [14]:
list_dict = [{"a": 1, "b": 2}, {"a": 5, "b": 10, "c": 20}]

In [15]:
pd.DataFrame(list_dict)

a   b     c
0  1   2   NaN
1  5  10  20.0

In [16]:
pd.DataFrame(list_dict,index=["first","second"])

a   b     c
first   1   2   NaN
second  5  10  20.0

In [17]:
pd.DataFrame(list_dict,index=["first","second"]).index

Index(['first', 'second'], dtype='object')

In [19]:
pd.DataFrame(list_dict,index=["first","second"]).reset_index(names="test")

test  a   b     c
0   first  1   2   NaN
1  second  5  10  20.0

# From a dict of tuples


In [3]:
dict_tuple_1 = {("a"):("A","AA","AAA")}

In [4]:
pd.DataFrame(dict_tuple)

a
0    A
1   AA
2  AAA

In [7]:
dict_tuple_2 = {("char", "a"):("A","AA","AAA"),("char","b"):("B","BB","BBB")} # MultiIndexed in columns with two elemnents tuple

In [8]:
pd.DataFrame(dict_tuple_2)

char     
     a    b
0    A    B
1   AA   BB
2  AAA  BBB

In [11]:
dict_tuple_3 = {("char", "a"):{("char","ONE"):"A",("char","TWO"):"AA",("char","THREE"):"AAA"},("char","b"):{("char","ONE"):"B",("char","TWO"):"BB",("char","THREE"):"BBB"}} # MultiIndexed in index and columns with dict of tuples

In [12]:
pd.DataFrame(dict_tuple_3)

char     
              a    b
char ONE      A    B
     TWO     AA   BB
     THREE  AAA  BBB

# From a Series

In [38]:
ser = pd.Series(range(3), index=list("abc"), name="ser")

In [39]:
ser

a    0
b    1
c    2
Name: ser, dtype: int64

In [40]:
df_ser = pd.DataFrame(ser)

In [41]:
df_ser

ser
a    0
b    1
c    2

# Index object 

In [15]:
index_dict = {
    "one": pd.Series([1.0, 2.0, 3.0, 5.0], index=["a", "b", "c","e"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

In [16]:
df_index_dic = pd.DataFrame(index_dict)

In [17]:
df_index_dic.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [18]:
df_index_dic.index.difference(['a']) # Create a new Index object based on index without 'a' in it

Index(['b', 'c', 'd', 'e'], dtype='object')

In [19]:
df_index_dic.index.append(df_index_dic.columns) # Create a new Index object with index and columns Index object

Index(['a', 'b', 'c', 'd', 'e', 'one', 'two'], dtype='object')

In [20]:
df_index_dic.index.append(df_index_dic.columns).is_unique

True

In [21]:
df_index_dic.index.append(df_index_dic.columns).isin(['m'])

array([False, False, False, False, False, False, False])

In [22]:
for i in df_index_dic.itertuples():
    print(i)

Pandas(Index='a', one=1.0, two=1.0)
Pandas(Index='b', one=2.0, two=2.0)
Pandas(Index='c', one=3.0, two=3.0)
Pandas(Index='d', one=nan, two=4.0)
Pandas(Index='e', one=5.0, two=nan)


In [23]:
s = pd.Series(range(5))
t = pd.Series([True,False])
s.where(t,99)

0     0
1    99
2    99
3    99
4    99
dtype: int64

In [24]:
df = pd.DataFrame({"A": np.arange(8), "B":list("aabbbbcc")})

In [25]:
df.groupby("B").filter(lambda x: len(x)>2)

A  B
2  2  b
3  3  b
4  4  b
5  5  b

In [26]:
df.groupby("B").apply(lambda x: len(x))

B
a    2
b    4
c    2
dtype: int64

In [27]:
df

A  B
0  0  a
1  1  a
2  2  b
3  3  b
4  4  b
5  5  b
6  6  c
7  7  c

In [80]:
list = np.random.randint(1,20,10)
index = np.random.randint(1,20,list.shape[0])
list,index

(array([10, 14, 17,  2, 13,  3, 18, 16, 15,  7]),
 array([15, 14, 18, 15, 19,  7,  7,  1, 13,  4]))

In [81]:
unsorted_ser = pd.Series(list,index=index)

In [82]:
unsorted_ser.sort_index()

1     16
4      7
7      3
7     18
13    15
14    14
15    10
15     2
18    17
19    13
dtype: int32

In [83]:
unsorted_ser.sort_values()

15     2
7      3
4      7
15    10
19    13
14    14
13    15
1     16
18    17
7     18
dtype: int32

In [24]:
s_2 = pd.Series(np.arange(5)+1)
s_2.info(),s_2.astype('int64').info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int32
dtypes: int32(1)
memory usage: 148.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 168.0 bytes


(None, None)

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 168.0 bytes
