In [3]:
print("Hello")

Hello


In [4]:
%history

python -V
print("Hello")
print("Hello")
%history


In [5]:
!ipconfig


Windows IP Configuration


Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Mobile Broadband adapter Cellular:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : cn.ao.ericsson.se
   Link-local IPv6 Address . . . . . : fe80::35c5:2654:79da:80f6%17
   IPv4 Address. . . . . . . . . . . : 100.99.198.216
   Subnet Mask . . . . . . . . . . . : 255.255.252.0
   Default Gateway . . . . . . . . . : 100.99.196.1

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 


In [8]:
import numpy as np
tmp = np.arange(10000).reshape(100,100)

In [9]:
tmp.dtype

dtype('int32')

In [14]:
b = np.arange(12).reshape(3,4)

In [15]:
b.sum(axis=0)

array([12, 15, 18, 21])

# 打印矩阵中满足大于4的值

In [18]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

#改变形状

In [21]:
a2 = np.arange(12).reshape(3, 4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a.ravel() # flat, 多维转一维

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
a.T # transpose, 转置

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])