# PREPARATION

In [1]:
# # a) Click on JupyterHub File – New – Notebook in the upper left corner
# # of the page button to create a new Notebook Used to save the
# # content of this exercise
# # b) Select Kernel for Python 3
# # c) As in the previous exercise, modify the notebook File name:
# # numpy.ipynb
# # d) Enter import numpy as np in the first code box and try to execute
# # it to confirm that there are no errors, indicating that the numpy
# # library has been loaded successfully. In subsequent exercises, np
# # will be used instead of numpy as an abbreviation.
import numpy as np

In [20]:
# a) Using np.random.randn function creates a 3*4 array x and
# use sum and mean function to calculate:
x = np.random.randn(3, 4)
x

array([[-2.12829248,  0.12330854, -1.45771201, -1.64923865],
       [ 0.75667582, -0.79725572, -0.48623222,  0.78729426],
       [-0.15485609,  0.43591776,  1.16426052,  0.52863373]])

In [22]:
# o Sum and average of this array as a whole
print("Whole array")
x.sum(), x.mean()

Whole array


(-2.877496533108581, -0.23979137775904844)

In [23]:
# o Sum and average of each row
print("Each Row")
x.sum(axis=1), x.mean(axis=1)

Each Row


(array([-5.1119346 ,  0.26048215,  1.97395592]),
 array([-1.27798365,  0.06512054,  0.49348898]))

In [24]:
# o sum and mean of each column
print("Each Column")
x.sum(axis=0), x.mean(axis=0)

Each Column


(array([-1.52647274, -0.23802942, -0.77968371, -0.33331066]),
 array([-0.50882425, -0.07934314, -0.25989457, -0.11110355]))

In [31]:
# b) Using np.one s and reshape to create a 2*2 array a with all member values 1.
a = np.ones(4).reshape(2, 2)
a

array([[1., 1.],
       [1., 1.]])

In [33]:
# c) Use np.insert change array a shape to 2*3 keeping all member values 1 and assign this new array to b.
b = np.ones(6).reshape(2, 3)
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# d) Use np.insert again change array b to 3*3 keeping the all member values as 1 and assign this new array to c.
c = np.ones(9).reshape(3, 3)
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# e) Using np.append change array c shape to 3 * 4 setting the value of the new column member to 2 and assign it to array d
d = np.append(c, (np.ones(3) * 2).reshape(3, 1), axis=1)
d

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [55]:
# f) Using np.append again change array d shape to 6*4 by adding 3 new lines to it and assigned to array e.
e = np.append(d, d, axis=0)
e

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [57]:
# g) Utilize np.unique function prints the unique value information of the entire array e, rows, and columns respectively.
np.unique(e), np.unique(e, axis=0), np.unique(e, axis=1)

(array([1., 2.]),
 array([[1., 1., 1., 2.]]),
 array([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]]))

<!-- # CREATE NUMPY ARRAY -->