# PREPARATION

In [3]:
# # a) Click on JupyterHub File – New – Notebook in the upper left corner
# # of the page button to create a new Notebook Used to save the
# # content of this exercise
# # b) Select Kernel for Python 3
# # c) As in the previous exercise, modify the notebook File name:
# # numpy.ipynb
# # d) Enter import numpy as np in the first code box and try to execute
# # it to confirm that there are no errors, indicating that the numpy
# # library has been loaded successfully. In subsequent exercises, np
# # will be used instead of numpy as an abbreviation.
import numpy as np

In [11]:
# a) Create a one-dimensional array a with member values ranging
# from 1 to 10 integers
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# b) Create a one-dimensional array b with member values ranging
# from -10 to -1 integers
b = np.arange(-10, 0)
b

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [13]:
# c) create array c, its value is a+b and check the value content
c = a + b
c

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [14]:
# d) create array d, whose value is a * b and check the value content
d = a * b
d

array([-10, -18, -24, -28, -30, -30, -28, -24, -18, -10])

In [16]:
# e) Use sum function to calculate the mean of array a
sum(a) / len(a)

5.5

In [21]:
# f) Use the comparison way to find the elements of the b array that are greater than -5 and count the numbers.
(b > -5), (b > -5).sum()

(array([False, False, False, False, False, False,  True,  True,  True,
         True]),
 4)

<!-- # CREATE NUMPY ARRAY -->