# PREPARATION

In [10]:
# # a) Click on JupyterHub File – New – Notebook in the upper left corner
# # of the page button to create a new Notebook Used to save the
# # content of this exercise
# # b) Select Kernel for Python 3
# # c) As in the previous exercise, modify the notebook File name:
# # numpy.ipynb
# # d) Enter import numpy as np in the first code box and try to execute
# # it to confirm that there are no errors, indicating that the numpy
# # library has been loaded successfully. In subsequent exercises, np
# # will be used instead of numpy as an abbreviation.
import numpy as np

<!-- # CREATE NUMPY ARRAY -->

In [8]:
# a) Create a list object containing 3 member of integer type, named:
# list_integer
list_integer = [1, 2, 3]
list_integer.__class__


list

In [9]:
# b) Create a tuple object, which contains 3 floating-point type
# members with a decimal point of 1 digit, named tuple_float
tuple_float = (0.1, 0.2, 0.3)
tuple_float.__class__

tuple

In [38]:
# c) Use the np.array method to construct two new ndarray objects
# based on the two newly created objects, named: array_list and
# array_tuple
# d) During the creation process, try to use the TAB completion
# function to achieve automatic completion of methods and
# variables.
# e) Then, print the basic results of the created objects separately, for
# example:
array_list = np.array(list_integer)
array_tuple = np.array(tuple_float)
array_list, array_tuple

(array([1, 2, 3]), array([0.1, 0.2, 0.3]))

In [39]:
# f) View the basic information of the newly created ndarray objects
# through the type function, shape and dtype attributes respectively
type(array_list), type(array_tuple), array_list.dtype, array_tuple.dtype, array_list.shape, array_tuple.shape

(numpy.ndarray, numpy.ndarray, dtype('int32'), dtype('float64'), (3,), (3,))

In [42]:
# g) Use the np.arange method to create an ndarray object, which is all even numbers from 1 to 20 :
array_even = np.arange(2, 21, 2)
array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
# h) Use list_integer and tuple_float to create a 2*3 array and use the shape attribute to confirm the shape of the result.:
array_2_3 = np.array([list_integer, tuple_float])
array_2_3, array_2_3.shape

(array([[1. , 2. , 3. ],
        [0.1, 0.2, 0.3]]),
 (2, 3))

In [49]:
# i) View the array just created through the type attribute. Please confirm the data type after combining integer data and floating point data.
array_even, array_even.dtype, array_2_3, array_2_3.dtype

(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]),
 dtype('int32'),
 array([[1. , 2. , 3. ],
        [0.1, 0.2, 0.3]]),
 dtype('float64'))

In [53]:
# j) Recreate array_list object and set its data type to float 64 to see the changes in the results:
array_list = np.array(list_integer, dtype='float64')
array_list, array_list.dtype

(array([1., 2., 3.]), dtype('float64'))

In [56]:
# k) Use the np.ones and multiplication function to create an ndarray with a shape of 4 * 4 and an element value of 10 :
np.ones((4, 4)), np.ones((4, 4)) * 10

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]]))