# PREPARATION

In [1]:
# # a) Click on JupyterHub File – New – Notebook in the upper left corner
# # of the page button to create a new Notebook Used to save the
# # content of this exercise
# # b) Select Kernel for Python 3
# # c) As in the previous exercise, modify the notebook File name:
# # numpy.ipynb
# # d) Enter import numpy as np in the first code box and try to execute
# # it to confirm that there are no errors, indicating that the numpy
# # library has been loaded successfully. In subsequent exercises, np
# # will be used instead of numpy as an abbreviation.
import numpy as np

In [19]:
# a) Use the np.random.randn function to create two arrays x and y respectively, with the number of members being 10. 
# Because they are random values, the output of the following examples will be different from your running results, for reference only.
x = np.random.randn(10)
y = np.random.randn(10)
x, y

(array([ 0.55463786,  0.80097669,  0.77949853,  1.13908322, -0.56497422,
         1.04869483, -0.1674351 ,  0.6862208 , -0.36359509,  1.16810993]),
 array([ 1.07245807,  0.18237223, -0.67045402,  0.99580564, -0.49885598,
        -0.37376171,  0.81337331,  0.06002768,  0.22356147, -0.21029625]))

In [20]:
# b) Use the np.maximum method to find the maximum value of the element at the same index position in x, y, similar to the output:
max = np.maximum(x, y)
max

array([ 1.07245807,  0.80097669,  0.77949853,  1.13908322, -0.49885598,
        1.04869483,  0.81337331,  0.6862208 ,  0.22356147,  1.16810993])

In [21]:
# c) Then use the np.abs method to take the absolute value of the value in x, y, 
# and then use the np.maximum method again to find the maximum value of the element at the same index position in x, y.
max_abs = np.maximum(np.abs(x), np.abs(y))
np.abs(x), np.abs(y), max_abs

(array([0.55463786, 0.80097669, 0.77949853, 1.13908322, 0.56497422,
        1.04869483, 0.1674351 , 0.6862208 , 0.36359509, 1.16810993]),
 array([1.07245807, 0.18237223, 0.67045402, 0.99580564, 0.49885598,
        0.37376171, 0.81337331, 0.06002768, 0.22356147, 0.21029625]),
 array([1.07245807, 0.80097669, 0.77949853, 1.13908322, 0.56497422,
        1.04869483, 0.81337331, 0.6862208 , 0.36359509, 1.16810993]))

In [22]:
# d) Use np.equal to determine the difference between the two
# maximum values and calculate the different amounts:
np.equal(max, max_abs), np.equal(max, max_abs).sum()

(array([ True,  True,  True,  True, False,  True,  True,  True, False,
         True]),
 8)

<!-- # CREATE NUMPY ARRAY -->