# PREPARATION

In [1]:
# # a) Click on JupyterHub File – New – Notebook in the upper left corner
# # of the page button to create a new Notebook Used to save the
# # content of this exercise
# # b) Select Kernel for Python 3
# # c) As in the previous exercise, modify the notebook File name:
# # numpy.ipynb
# # d) Enter import numpy as np in the first code box and try to execute
# # it to confirm that there are no errors, indicating that the numpy
# # library has been loaded successfully. In subsequent exercises, np
# # will be used instead of numpy as an abbreviation.
import numpy as np

In [4]:
# a) Using np.arange to create a new array a with member values
# ranging from 1 to 10 integers
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# b) Access the 3rd, 5th-10th, and penultimate data respectively
a[2], a[4:].tolist(), a[-2]

(3, [5, 6, 7, 8, 9, 10], 9)

In [13]:
# c) Multiply values in the even-numbered index of array a by 2 and print the result
a[1::2] * 2

array([ 4,  8, 12, 16, 20])

In [14]:
# d) Using np.arange to create a new array b with member values ranging from 1 to 24 .
b = np.arange(1, 25)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
# e) Use the reshape function to convert it into 3 rows and 8 columns array.
b.reshape(3, 8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [18]:
# f) Use the reshape function to convert it into 4 rows and 6 columns, and then assign it to array c.
c = b.reshape(4, 6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [19]:
# g) Get the third row data of array c.
c[2]

array([13, 14, 15, 16, 17, 18])

In [20]:
# h) Get the third column data of array c.
c[::,2]

array([ 3,  9, 15, 21])

In [29]:
# i) Create a new array: names, fill in 4 member variables: 'Bob', 'Will', ' Joe', 'Mary '
names = np.array(['Bob', 'Will', 'Joe', 'Mary '])
names

array(['Bob', 'Will', 'Joe', 'Mary '], dtype='<U5')

In [30]:
# j) Assume that each row of data in c corresponds to each of the 4 members in names (for example, c[0] is Bob's data, and so on), 
# then please take out the data of Bob and Joe based on the name as a condition at one time:
c[(names == 'Bob') | (names == 'Joe')]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

<!-- # CREATE NUMPY ARRAY -->