# PREPARATION

In [1]:
# # a) Click on JupyterHub File – New – Notebook in the upper left corner
# # of the page button to create a new Notebook Used to save the
# # content of this exercise
# # b) Select Kernel for Python 3
# # c) As in the previous exercise, modify the notebook File name:
# # numpy.ipynb
# # d) Enter import numpy as np in the first code box and try to execute
# # it to confirm that there are no errors, indicating that the numpy
# # library has been loaded successfully. In subsequent exercises, np
# # will be used instead of numpy as an abbreviation.
import numpy as np

In [6]:
# a) Use the flat attribute and ravel function of the array to "flatten" the members in the array c from the previous exercise respectively 
# and then iterate and print to see the flattened results and output order:
c = np.arange(1, 25).reshape(4, 6)
c.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [7]:
for i in c.ravel():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [8]:
# b) Change array c’s shape to 6*4 and assign it to the new array d.
d = c.reshape(6, 4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [13]:
# c) Use the T attribute and the transpose function to create the
# transposition of the d array respectively and compare whether the
# two results are consistent (same shape, same elements).
d.T == d.transpose()

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [22]:
# d) Use vstack and hstack to stack c and d vertically and horizontally
# respectively (note: c and d have different shapes):
np.vstack((c, d.T)), np.hstack((c, d.T))

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23],
        [ 4,  8, 12, 16, 20, 24]]),
 array([[ 1,  2,  3,  4,  5,  6,  1,  5,  9, 13, 17, 21],
        [ 7,  8,  9, 10, 11, 12,  2,  6, 10, 14, 18, 22],
        [13, 14, 15, 16, 17, 18,  3,  7, 11, 15, 19, 23],
        [19, 20, 21, 22, 23, 24,  4,  8, 12, 16, 20, 24]]))

In [26]:
# e) Using np.sort function sorts the stacked array in previous step and will get the following results:
np.sort(np.vstack((c, d.T)), axis=0), np.sort(np.hstack((c, d.T)))

(array([[ 1,  2,  3,  4,  5,  6],
        [ 1,  5,  9, 10, 11, 12],
        [ 2,  6,  9, 13, 17, 18],
        [ 3,  7, 10, 14, 17, 21],
        [ 4,  8, 11, 15, 18, 22],
        [ 7,  8, 12, 16, 19, 23],
        [13, 14, 15, 16, 20, 24],
        [19, 20, 21, 22, 23, 24]]),
 array([[ 1,  1,  2,  3,  4,  5,  5,  6,  9, 13, 17, 21],
        [ 2,  6,  7,  8,  9, 10, 10, 11, 12, 14, 18, 22],
        [ 3,  7, 11, 13, 14, 15, 15, 16, 17, 18, 19, 23],
        [ 4,  8, 12, 16, 19, 20, 20, 21, 22, 23, 24, 24]]))

<!-- # CREATE NUMPY ARRAY -->