In [2]:
import numpy as np

# CREATE NUMPY ARRAY

In [101]:
list_integer = [1,2,3]

tuple_float = (1.1,2.2,3.3)

array_list = np.array(list_integer)

array_tuple = np.array(tuple_float)

array_list,array_tuple


(array([1, 2, 3]), array([1.1, 2.2, 3.3]))

In [102]:
type(array_list),type(array_tuple),array_list.dtype,array_tuple.dtype,array_list.shape,array_tuple.shape

(numpy.ndarray, numpy.ndarray, dtype('int32'), dtype('float64'), (3,), (3,))

In [13]:
np.arange(2,22,2),np.arange(2,22,2).dtype

(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]), dtype('int32'))

In [11]:
np.array([list_integer,tuple_float]),np.array([list_integer,tuple_float]).shape

(array([[1. , 2. , 3. ],
        [1.1, 2.2, 3.3]]),
 (2, 3))

In [12]:
np.array([list_integer,tuple_float]).dtype

dtype('float64')

In [18]:
array_list = np.array(list_integer,dtype='float64')

In [20]:
array_list,array_list.dtype

(array([1., 2., 3.]), dtype('float64'))

In [3]:
np.ones((4,4))*10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

# BASIC OPERATIONS

In [9]:
a = np.arange(1,11)
b = np.arange(-10,0)

In [11]:
c = a+b
c

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [12]:
d = a*b
d

array([-10, -18, -24, -28, -30, -30, -28, -24, -18, -10])

In [15]:
(a > 5)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [18]:
a.sum()/len(a)

5.5

In [20]:
b > -5, (b > -5).sum()

(array([False, False, False, False, False, False,  True,  True,  True,
         True]),
 4)

In [22]:
c > a

array([False, False, False, False, False, False, False, False, False,
       False])

# INDEXING AND DATA ACCESS

In [24]:
a = np.arange(1,11)

In [30]:
a[2],a[4:].tolist(),a[-2]

(3, [5, 6, 7, 8, 9, 10], 9)

In [33]:
a[1::2]*2

array([ 4,  8, 12, 16, 20])

In [36]:
b = np.arange(1,25)

In [37]:
b.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [43]:
c = b.reshape(4,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [44]:
c[2,:]

array([13, 14, 15, 16, 17, 18])

In [45]:
c[:,2]

array([ 3,  9, 15, 21])

In [46]:
names = np.array(['Bob', 'Will', 'Joe','Mary'])

In [47]:
names

array(['Bob', 'Will', 'Joe', 'Mary'], dtype='<U4')

In [59]:
c[(names == 'Bob') | (names == 'Joe')]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

# CHANGE ARRAY SHAPE

In [61]:
for i in c.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [64]:
c.ravel()
# for i in c.ravel():
#     print(i)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [78]:
d = c.reshape(6,4)
d.transpose() == d.T

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [79]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [84]:
np.hstack((c,d.T))

array([[ 1,  2,  3,  4,  5,  6,  1,  5,  9, 13, 17, 21],
       [ 7,  8,  9, 10, 11, 12,  2,  6, 10, 14, 18, 22],
       [13, 14, 15, 16, 17, 18,  3,  7, 11, 15, 19, 23],
       [19, 20, 21, 22, 23, 24,  4,  8, 12, 16, 20, 24]])

In [96]:
np.sort(np.hstack((c,d.T)))

array([[ 1,  1,  2,  3,  4,  5,  5,  6,  9, 13, 17, 21],
       [ 2,  6,  7,  8,  9, 10, 10, 11, 12, 14, 18, 22],
       [ 3,  7, 11, 13, 14, 15, 15, 16, 17, 18, 19, 23],
       [ 4,  8, 12, 16, 19, 20, 20, 21, 22, 23, 24, 24]])

In [93]:
np.vstack((c,d.T))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23],
       [ 4,  8, 12, 16, 20, 24]])

In [95]:
np.sort(np.vstack((c,d.T)),axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  5,  9, 10, 11, 12],
       [ 2,  6,  9, 13, 17, 18],
       [ 3,  7, 10, 14, 17, 21],
       [ 4,  8, 11, 15, 18, 22],
       [ 7,  8, 12, 16, 19, 23],
       [13, 14, 15, 16, 20, 24],
       [19, 20, 21, 22, 23, 24]])

# UFUNC OPERATIONS

In [87]:
x = np.random.randn(10)
y = np.random.randn(10)
max1 = np.maximum(x,y)
max1

array([-0.32141676,  0.01847806,  0.0407462 ,  0.72235306,  0.27720061,
        1.26229279,  1.32221022,  1.95550421, -1.00065708,  0.23983974])

In [88]:
max2 =np.maximum(np.abs(x),np.abs(y))
max2

array([2.13188235, 1.22151757, 0.13738144, 0.74742505, 0.62555621,
       1.26229279, 1.32221022, 1.95550421, 1.18047047, 0.23983974])

In [91]:
np.equal(max1,max2),np.equal(max1,max2).sum()

(array([False, False, False, False, False,  True,  True,  True, False,
         True]),
 4)

# ARRAY ELEMENT OPERATIONS

In [109]:
x = np.random.randn(3,4)
x

array([[-1.19699796,  0.65237723,  1.31444592, -0.55038981],
       [ 0.9823068 ,  0.34662228, -0.26611348, -0.08597678],
       [ 2.97667412,  0.34155429,  1.91458736, -1.57691105]])

In [110]:
print("Whole array")
x.sum(),x.mean()

Whole array


(4.8521789180629185, 0.40434824317190987)

In [113]:
print("Each Column")
x.sum(axis=0),x.mean(axis=0)

Each Row


(array([ 2.76198296,  1.3405538 ,  2.9629198 , -2.21327764]),
 array([ 0.92066099,  0.44685127,  0.98763993, -0.73775921]))

In [114]:
print("Each Row")
x.sum(axis=1),x.mean(axis=1)

Each Column


(array([0.21943539, 0.97683881, 3.65590472]),
 array([0.05485885, 0.2442097 , 0.91397618]))

In [47]:
a = np.ones(4).reshape(2,2)

In [48]:
b = np.insert(a,1,[1],axis=1)

In [49]:
c = np.insert(b,1,[1],axis=0)

In [50]:
a,b,c

(array([[1., 1.],
        [1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [68]:
new_column = np.ones(len(c[:,0]))*2
d = np.append(c,new_column[:,np.newaxis],axis=1)

In [78]:
e = np.append(d,d,axis=0)
e

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [81]:
np.unique(e),np.unique(e,axis=1),np.unique(e,axis=0)

(array([1., 2.]),
 array([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]]),
 array([[1., 1., 1., 2.]]))